-- Destructive local/test reset for SemRisk relational twin.
DROP SCHEMA IF EXISTS pharma CASCADE;
DROP SCHEMA IF EXISTS governance CASCADE;
DROP SCHEMA IF EXISTS enterprise CASCADE;
DROP SCHEMA IF EXISTS treatment CASCADE;
DROP SCHEMA IF EXISTS assessment CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS ref CASCADE;
DROP SCHEMA IF EXISTS staging CASCADE;
DROP SCHEMA IF EXISTS meta CASCADE;
